pipeline {
    agent any

    environment {
        ARTIFACTORY_PASS = credentials('ARTIFACTORY_PASS')
        CONAN_USER = 'sds'
        MASTER_BRANCH = 'master'
        TESTING_BRANCH = 'testing/v*'
        STABLE_BRANCH = 'stable/v*'
        LAST_COMMITS = ''
        built_chain = ''
        failed_pkg = ""
    }

    parameters {
        string(defaultValue: "", description: 'UpstreamTriggered', name: 'upstream_triggered')
    }

    stages {
        stage('Adjust Tag for Master/PR') {
            when { not { anyOf {
                branch "${TESTING_BRANCH}"
                branch "${STABLE_BRANCH}"
            } } }
            steps {
                script {
                    sh(script: "sed -Ei 's,version = .*\"([[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+).*,version = \"\\1-${env.BUILD_NUMBER}\",' conanfile.py")
                    BUILD_MISSING = "--build missing"
                    LAST_COMMITS = sh(script: "git log -n 2 --pretty=short", returnStdout: true)
                }
            }
        }
        stage('Adjust for Testing/Stable') {
            when { anyOf {
                branch "${TESTING_BRANCH}"
                branch "${STABLE_BRANCH}"
            } }
            steps {
                script {
                    BUILD_MISSING = ""
                }
            }
        }

        stage('Get Version') {
            steps {
                script {
                    PROJECT = sh(script: "grep -m 1 'name =' conanfile.py | awk '{print \$3}' | tr -d '\n' | tr -d '\"'", returnStdout: true)
                    VER = sh(script: "grep -m 1 'version =' conanfile.py | awk '{print \$3}' | tr -d '\n' | tr -d '\"'", returnStdout: true)
                    CONAN_CHANNEL = sh(script: "echo ${BRANCH_NAME} | sed -E 's,(\\w+-?\\d*)/.*,\\1,' | sed -E 's,-,_,' | tr -d '\n'", returnStdout: true)
                    TAG = "${VER}@${CONAN_USER}/${CONAN_CHANNEL}"
                    slackSend color: '#0063D1', channel: '#sds-ci', message: "*${PROJECT}/${TAG}* is building."
                    env.pkg_version = "${PROJECT}/${TAG}"
                }
            }
        }

        stage('Tag Stable Build') {
            when { branch "${STABLE_BRANCH}" }
            steps {
                script {
                    TAG = "${VER}@"
                }
            }
        }

        stage('Build') {
            failFast true
            matrix {
                agent { label 'sds-builder' }
                axes {
                    axis {
                        name 'BUILD_TYPE'
                        values 'sanitize', 'debug', 'test'
                    }
                    axis {
                        name 'COVERAGE'
                        values 'False'
                } }
                excludes { exclude {
                    axis {
                        name 'BUILD_TYPE'
                        values 'sanitize', 'test'
                    }
                    axis {
                        name 'COVERAGE'
                        values 'True'
                    }
                } }

                stages {
                    stage('Adjust Tag for Master/PR') {
                        when { not { anyOf {
                            branch "${TESTING_BRANCH}"
                            branch "${STABLE_BRANCH}"
                        } } }
                        steps {
                            sh(script: "sed -Ei 's,version = .*\"([[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+).*,version = \"\\1-${env.BUILD_NUMBER}\",' conanfile.py")
                        }
                    }

                    stage("Build") {
                        when { allOf {
                            expression { "${COVERAGE}" == 'False' }
                            expression { "${BUILD_TYPE}" != 'sanitize' }
                        } }
                        steps {
                            sh "conan create ${BUILD_MISSING} -pr ${BUILD_TYPE} . ${PROJECT}/${TAG}"
                        }
                    }

                    stage("Sanitize") {
                        when { allOf {
                            expression { "${BUILD_TYPE}" == 'sanitize' }
                        } }
                        steps {
                            sh "conan create ${BUILD_MISSING} -o ${PROJECT}:sanitize=True -pr debug . ${PROJECT}/${TAG}"
                        }
                    }

                    stage("Deploy") {
                        when { allOf {
                            expression { "${COVERAGE}" == 'False' }
                            expression { "${BUILD_TYPE}" != 'sanitize' }
                            expression { !(env.BRANCH_NAME =~ /PR-/) }
                        } }
                        steps {
                            sh "conan user -r ebay-local -p ${ARTIFACTORY_PASS} _service_sds"
                            sh "conan upload ${PROJECT}/${TAG} -c --all -r ebay-local"
                        }
                    }

                    stage('Coverage') {
                        when { not { anyOf {
                            branch "${STABLE_BRANCH}"
                            expression { "${COVERAGE}" == 'False' }
                        } } }

                        stages {
                            stage("Adjust Sonar Branch") {
                                when {
                                    not {
                                        branch "${MASTER_BRANCH}"
                                    }
                                }
                                steps {
                                    sh "echo \"sonar.branch.target=${MASTER_BRANCH}\" >> sonar-project.properties"
                                }
                            }
                            stage("Code Coverage") {
                                steps {
                                    slackSend channel: '#sds-ci', message: "*${PROJECT}:${TAG}* is undergoing Code Coverage."
                                    sh "echo \"sonar.branch.name=${BRANCH_NAME}\" >> sonar-project.properties"
                                    sh "conan install -pr ${BUILD_TYPE} ${BUILD_MISSING} -o ${PROJECT}:coverage=True ."
                                    sh "build-wrapper-linux-x86-64 --out-dir /tmp/sonar conan build ."
                                    sh "find . -name \"*.gcno\" -exec gcov {} \\;"
                                    withSonarQubeEnv('sds-sonar')  {
                                        sh "sonar-scanner -Dsonar.projectBaseDir=. -Dsonar.projectVersion=\"${VER}\""
                                    }
                                }
                            }
                            stage("Quality Gate") {
                                steps {
                                    timeout(time: 30, unit: 'MINUTES') {
                                        waitForQualityGate abortPipeline: true
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        stage("Downstream Build") {
            when { allOf {
               expression { (env.BRANCH_NAME == "${MASTER_BRANCH}") }
               expression { (!"${upstream_triggered}") || ("${upstream_triggered}" == "") }
            } }
        
            stages {
                stage('Homestore') {
                    steps {
                        script {
                            built_chain = env.pkg_version
                            def hs_res = build job: "Homestore/${MASTER_BRANCH}", parameters: [[$class: 'StringParameterValue', name: 'upstream_triggered', value: 'true']], propagate: true
                            built_chain = "${built_chain}" + ", " + "$hs_res.buildVariables.pkg_version"
                        }
                    }
                    post {
                        failure { script { failed_pkg = "Homestore" } }
                    }
                }
                stage('SCST Connector') {
                    steps {
                        script {
                            built_chain = env.pkg_version
                            def scst_res = build job: "SCST Connector/${MASTER_BRANCH}", parameters: [[$class: 'StringParameterValue', name: 'upstream_triggered', value: 'true']], propagate: true
                            built_chain = "${built_chain}" + ", " + "scst_res.buildVariables.pkg_version"
                        }
                    }
                    post {
                        failure { script { failed_pkg = "SCST Connector" } }
                    }
                }
                stage('NuBlox Logstore') {
                    steps {
                        script {
                            def nls_res = build job: "Nublox Logstore/${MASTER_BRANCH}", parameters: [[$class: 'StringParameterValue', name: 'upstream_triggered', value: 'true']], propagate: true
                            built_chain = "${built_chain}" + ", " + "nls_res.buildVariables.pkg_version"
                        }
                    }
                    post {
                        failure { script { failed_pkg = "Nublox Logstore" } }
                    }
                }
                stage('Homestore BDev') {
                    steps {
                        script {
                            def hsbdev_res = build job: "Homestore Bdev/${MASTER_BRANCH}", parameters: [[$class: 'StringParameterValue', name: 'upstream_triggered', value: 'true']], propagate: true
                            built_chain = "${built_chain}" + ", " + "$hsbdev_res.buildVariables.pkg_version"
                        }
                    }
                    post {
                        failure { script { failed_pkg = "Homestore BDev" } }
                    }
                }
                stage('SPDK Connector') {
                    steps {
                        script {
                            def spdk_res = build job: "SPDK Connector/${MASTER_BRANCH}", parameters: [[$class: 'StringParameterValue', name: 'upstream_triggered', value: 'true']], propagate: true
                            built_chain = "${built_chain}" + ", " + "$spdk_res.buildVariables.pkg_version"
                        }
                    }
                    post {
                        failure { script { failed_pkg = "SPDK Connector" } }
                    }
                }
            }
        }
    }

    post {
        failure {
            script {
                if ("${failed_pkg}" != "") {
                    slackSend color: '#E43237', channel: '#homestore-build', message: "@here IOManager's downstream pkg - *${failed_pkg}* build failed.\n*URL:* ${BUILD_URL}\n*Last 2 commits:* ```${LAST_COMMITS}```\nIf result not expected, revert (aka `conan remove -r ebay-local`) these pkgs: ```${built_chain}```"
                }
            }
            slackSend color: '#E43237', channel: '#sds-ci', message: "*${PROJECT}/${TAG}* has had a failure : ${BUILD_URL}"
        }
        success {
            slackSend color: '#85B717', channel: '#sds-ci', message: "*${PROJECT}/${TAG}* has completed successfully."
        }
    }
}
