name: Build Commit

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      build-type:
        required: true
        type: string
      malloc-impl:
        required: true
        type: string
      prerelease:
        required: true
        type: string

jobs:
  SislDeps:
    uses: szmyd/sisl/.github/workflows/build_dependencies.yml@test_custom_action
    with:
      branch: stable/v8.x
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
  IOMgrDeps:
    needs: SislDeps
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: ${{ github.ref }}
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      testing: 'True'
