name: Build Commit

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      build-type:
        required: true
        type: string
      malloc-impl:
        required: true
        type: string
      prerelease:
        required: true
        type: string
      tooling:
        required: true
        type: string

jobs:
  SislForkDeps:
    uses: hkadayam/sisl/.github/workflows/build_dependencies.yml@master
    with:
      branch: master
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      tooling: None
    if: ${{ github.event_name != 'pull_request' }}

  IOMgrDeps:
    needs: SislForkDeps
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: ${{ github.ref }}
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      tooling: ${{ inputs.tooling }}
      testing: 'True'
    if: ${{ github.event_name != 'pull_request' }}

  IOMgrBuild:
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: ${{ github.ref }}
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      tooling: ${{ inputs.tooling }}
      testing: 'True'
    if: ${{ github.event_name == 'pull_request' }}
