name: IOManager Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - stable/v8.x

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-22.04"]
        build-type: ["Debug", "RelWithDebInfo"]
        malloc-impl: ["libc", "tcmalloc"]
        prerelease: ["True", "False"]
        tooling: ["Sanitize", "Coverage", "None"]
        exclude:
          - build-type: Debug
            prerelease: "False"
          - build-type: Debug
            tooling: None
          - build-type: Debug
            malloc-impl: tcmalloc
          - build-type: RelWithDebInfo
            malloc-impl: libc
          - build-type: RelWithDebInfo
            tooling: Sanitize
          - build-type: RelWithDebInfo
            tooling: Coverage
    uses: ./.github/workflows/build_commit.yml
    with:
      platform: ${{ matrix.platform }}
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}
      tooling: ${{ matrix.tooling }}
