name: IOManager PR Build

on:
  pull_request:
    branches:
      - master
      - stable/v8.x

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-22.04"]
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc"]
        prerelease: ["True", "False"]
        exclude:
          - malloc-impl: libc
            build-type: Release
            platform: ubuntu-22.04
          - prerelease: "False"
            build-type: Debug
    uses: ./.github/workflows/build_commit.yml
    with:
      platform: ${{ matrix.platform }}
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}
